name: "Stale handler"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@main
        id: stale
        with:
          stale-issue-message: "This issue is stale because it has been open 60 days with no activity."
          days-before-stale: 60
          days-before-close: -1
          stale-issue-label: "Stale"
          exempt-issue-milestones: true
          exempt-issue-labels: "blocked,wontfix"
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}
      - uses: actions/stale@main
        id: stale
        with:
          stale-pr-message: "This pull request is stale because it has been open for 2 days with no activity. "
          days-before-stale: 2
          days-before-close: -1
          stale-pr-label: "Stale"
          exempt-pr-labels: "blocked,wontfix"
          exempt-draft-pr: true
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}
